John test branch
idugan100/forecast-comp-fe pull request #1
Opened 2023-11-28 15:14 UTC by Thejohnmeyers

adding pass word conf

2023-11-30 14:33 UTC, idugan100 requested changes
Functionality looks good. Just need to undo changes we did to front end registration logic.

2023-11-30 14:33 UTC, idugan100 commented on src/App.js
I think we changed this to try to let you register for an account and forgot to put it back. Let's undo changes in this file.

2023-11-30 14:33 UTC, idugan100 commented on src/redux/reducers/status.js
I think we changed this to try to let you register for an account and forgot to put it back. Let's undo changes in this file.

2023-12-04 22:10 UTC, Thejohnmeyers commented on src/App.js
all good

2023-12-04 22:10 UTC, Thejohnmeyers commented on src/redux/reducers/status.js
all good

2023-12-04 22:11 UTC, idugan100 approved these changes

2023-12-04 22:12 UTC, merged